[2021-01-14 11:12:16,745] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: test_daily_0030.wait_daily 2021-01-13T00:30:00+00:00 [queued]>
[2021-01-14 11:12:16,760] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: test_daily_0030.wait_daily 2021-01-13T00:30:00+00:00 [queued]>
[2021-01-14 11:12:16,760] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-01-14 11:12:16,760] {taskinstance.py:881} INFO - Starting attempt 3 of 6
[2021-01-14 11:12:16,760] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-01-14 11:12:16,765] {taskinstance.py:901} INFO - Executing <Task(ExternalTaskSensor): wait_daily> on 2021-01-13T00:30:00+00:00
[2021-01-14 11:12:16,769] {standard_task_runner.py:54} INFO - Started process 13597 to run task
[2021-01-14 11:12:16,791] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'test_daily_0030', 'wait_daily', '2021-01-13T00:30:00+00:00', '--job_id', '26', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/test_daily_0030.py', '--cfg_path', '/var/folders/1c/xhkpty0142l7xwkrqtm3t9p80000gn/T/tmp33uo1x9q']
[2021-01-14 11:12:16,792] {standard_task_runner.py:78} INFO - Job 26: Subtask wait_daily
[2021-01-14 11:12:16,822] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: test_daily_0030.wait_daily 2021-01-13T00:30:00+00:00 [running]> 1.0.0.127.in-addr.arpa
[2021-01-14 11:12:16,836] {external_task_sensor.py:117} INFO - Poking for test_daily_0015.None on 2021-01-13T00:30:00+00:00 ... 
[2021-01-14 11:12:46,768] {local_task_job.py:159} WARNING - State of this instance has been externally set to success. Taking the poison pill.
[2021-01-14 11:12:46,775] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 13597
[2021-01-14 11:12:46,775] {taskinstance.py:955} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-01-14 11:12:46,783] {helpers.py:291} INFO - Process psutil.Process(pid=13597, status='terminated', exitcode=0, started='11:12:16') (13597) terminated with exit code 0
[2021-01-14 11:12:46,784] {local_task_job.py:102} INFO - Task exited with return code 0
