[2021-01-14 11:17:08,683] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: test_daily_0030.wait_monthly 2021-01-13T00:30:00+00:00 [queued]>
[2021-01-14 11:17:08,703] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: test_daily_0030.wait_monthly 2021-01-13T00:30:00+00:00 [queued]>
[2021-01-14 11:17:08,703] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-01-14 11:17:08,703] {taskinstance.py:881} INFO - Starting attempt 1 of 4
[2021-01-14 11:17:08,704] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-01-14 11:17:08,709] {taskinstance.py:901} INFO - Executing <Task(ExternalTaskSensor): wait_monthly> on 2021-01-13T00:30:00+00:00
[2021-01-14 11:17:08,713] {standard_task_runner.py:54} INFO - Started process 13767 to run task
[2021-01-14 11:17:08,735] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'test_daily_0030', 'wait_monthly', '2021-01-13T00:30:00+00:00', '--job_id', '28', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/test_daily_0030.py', '--cfg_path', '/var/folders/1c/xhkpty0142l7xwkrqtm3t9p80000gn/T/tmp7y7c1xl2']
[2021-01-14 11:17:08,737] {standard_task_runner.py:78} INFO - Job 28: Subtask wait_monthly
[2021-01-14 11:17:08,769] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: test_daily_0030.wait_monthly 2021-01-13T00:30:00+00:00 [running]> 1.0.0.127.in-addr.arpa
[2021-01-14 11:17:08,784] {external_task_sensor.py:117} INFO - Poking for test_monthly.None on 2021-01-13T00:30:00+00:00 ... 
[2021-01-14 11:17:13,664] {local_task_job.py:159} WARNING - State of this instance has been externally set to success. Taking the poison pill.
[2021-01-14 11:17:13,671] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 13767
[2021-01-14 11:17:13,671] {taskinstance.py:955} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-01-14 11:17:13,679] {helpers.py:291} INFO - Process psutil.Process(pid=13767, status='terminated', exitcode=0, started='11:17:08') (13767) terminated with exit code 0
[2021-01-14 11:17:13,680] {local_task_job.py:102} INFO - Task exited with return code 0
[2021-01-14 13:17:43,702] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: test_daily_0030.wait_monthly 2021-01-13T00:30:00+00:00 [queued]>
[2021-01-14 13:17:43,714] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: test_daily_0030.wait_monthly 2021-01-13T00:30:00+00:00 [queued]>
[2021-01-14 13:17:43,714] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-01-14 13:17:43,714] {taskinstance.py:881} INFO - Starting attempt 1 of 3
[2021-01-14 13:17:43,714] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-01-14 13:17:43,719] {taskinstance.py:901} INFO - Executing <Task(ExternalTaskSensor): wait_monthly> on 2021-01-13T00:30:00+00:00
[2021-01-14 13:17:43,723] {standard_task_runner.py:54} INFO - Started process 25489 to run task
[2021-01-14 13:17:43,746] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'test_daily_0030', 'wait_monthly', '2021-01-13T00:30:00+00:00', '--job_id', '40', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/test_daily_0030.py', '--cfg_path', '/var/folders/1c/xhkpty0142l7xwkrqtm3t9p80000gn/T/tmpvf3qupe9']
[2021-01-14 13:17:43,747] {standard_task_runner.py:78} INFO - Job 40: Subtask wait_monthly
[2021-01-14 13:17:43,779] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: test_daily_0030.wait_monthly 2021-01-13T00:30:00+00:00 [running]> 1.0.0.127.in-addr.arpa
[2021-01-14 13:17:43,795] {external_task_sensor.py:117} INFO - Poking for test_monthly.hello_task on 2021-01-13T00:30:00+00:00 ... 
[2021-01-14 13:17:43,798] {dagbag.py:417} INFO - Filling up the DagBag from /Users/wonji/WJ/study/study_airflow/dags/test_monthly.py
[2021-01-14 13:17:48,695] {local_task_job.py:159} WARNING - State of this instance has been externally set to success. Taking the poison pill.
[2021-01-14 13:17:48,701] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 25489
[2021-01-14 13:17:48,701] {taskinstance.py:955} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-01-14 13:17:48,709] {helpers.py:291} INFO - Process psutil.Process(pid=25489, status='terminated', exitcode=0, started='13:17:43') (25489) terminated with exit code 0
[2021-01-14 13:17:48,710] {local_task_job.py:102} INFO - Task exited with return code 0
